"""empty message

Revision ID: f0641006a8d4
Revises: c16727961897
Create Date: 2024-05-25 13:17:25.289645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0641006a8d4'
down_revision = 'c16727961897'
branch_labels = None
depends_on = None

from sqlalchemy.engine.reflection import Inspector

def upgrade():
    # Verificar si la columna 'photo_name' ya existe en la tabla 'cart_item'
    inspector = Inspector.from_engine(op.get_bind())
    columns = inspector.get_columns('cart_item')
    has_photo_name_column = any(column['name'] == 'photo_name' for column in columns)

    # Agregar la columna 'photo_name' si no existe
    if not has_photo_name_column:
        with op.batch_alter_table('cart_item', schema=None) as batch_op:
            batch_op.add_column(sa.Column('photo_name', sa.String(length=100), nullable=False, server_default='default_value'))

    # Verificar si la columna 'photo_price' ya existe en la tabla 'cart_item'
    has_photo_price_column = any(column['name'] == 'photo_price' for column in columns)

    # Agregar la columna 'photo_price' si no existe
    if not has_photo_price_column:
        with op.batch_alter_table('cart_item', schema=None) as batch_op:
            batch_op.add_column(sa.Column('photo_price', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('photo_price')
        batch_op.drop_column('photo_name')

    # ### end Alembic commands ###

